name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.101" # Use the exact version of .NET your project requires

      - name: Install dependencies and build
        run: |
          cd backend
          dotnet restore
          dotnet build --no-restore

      - name: Publish
        run: |
          cd backend
          dotnet publish --no-restore
