name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # specify your Node.js version

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Build
      run: |
        cd backend
        npm run build # modify this line if your build command differs

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'linkupBackend'
        slot-name: 'production' # Modify or remove this if you are not using slots
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: backend

